apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-with-pvc
  labels:
   app: nginx-with-pvc
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: nginx-with-pvc
  template:
    metadata:
      labels:
        app: nginx-with-pvc
    spec:
      containers:
      - name: nginx-with-pvc
        image: nginx
        ports:
          - name: web
            containerPort: 80
        volumeMounts:
          - name: nfs
            mountPath: /usr/share/nginx/html
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs
