apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvc-web
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: pvc-web
  template:
    metadata:
      labels:
        app: pvc-web
    spec:
      containers:
      - name: pvc-web
        image: nginx
        ports:
          - name: web-pvc
            containerPort: 80
        volumeMounts:
          - name: nfs-pvc
            mountPath: /usr/share/nginx/html
      volumes:
      - name: nfs-pvc
        persistentVolumeClaim:
          claimName: test-claim